const instagramTiles = [
  ["https://goldcoast-accom.com.au/wp-content/uploads/2026/02/Palm-Beach.webp", "Palm Beach coastline"],
  ["https://goldcoast-accom.com.au/wp-content/uploads/2024/09/48447-294141-0BIcAc3-IFhu0HJ2wRSbJT5ATfOCFxz18Ny-anB8AqU-66a45497c9b4d-1200x800.webp", "Panoramic Gold Coast accommodation"],
  ["https://goldcoast-accom.com.au/wp-content/uploads/2024/10/yacht.png", "Private yacht experience on the Gold Coast"],
  ["https://goldcoast-accom.com.au/wp-content/uploads/2026/01/48447-269118-eBvpx0MNeHOiclavT1y-KMaeg4xFOMKIYnOmkPADdjI-6639ea5885aef-1024x684.webp", "Coastal holiday home interior"],
  ["https://goldcoast-accom.com.au/wp-content/uploads/2024/10/Defender-Pic-1.jpg", "Gold Coast adventure experience"],
  ["https://goldcoast-accom.com.au/wp-content/uploads/2026/02/Burleigh.jpg", "Burleigh Heads coastline"],
];

function InstagramGallery(){return <section className="instagram-section" aria-labelledby="instagram-title"><div className="instagram-heading"><div><p className="eyebrow">Stay inspired</p><h2 id="instagram-title">Follow the coast with us.</h2></div><a className="instagram-handle" href="https://www.instagram.com/goldcoastaccom/" target="_blank" rel="noreferrer" aria-label="Follow Gold Coast Accom on Instagram (opens in a new tab)"><span aria-hidden="true">◎</span> @goldcoastaccom</a></div><div className="instagram-grid">{instagramTiles.map(([src,alt],index)=><a href="https://www.instagram.com/goldcoastaccom/" target="_blank" rel="noreferrer" className="instagram-tile" key={src} aria-label={`View ${alt} on Gold Coast Accom's Instagram`}><img src={src} alt={alt} loading="lazy" decoding="async"/><span className="instagram-overlay"><b aria-hidden="true">◎</b><small>View on Instagram</small></span><i>0{index+1}</i></a>)}</div></section>}

export default function SiteFooter(){return <><InstagramGallery/><footer><div className="footer-brand"><a className="brand" href="/"><img src="/assets/gold-coast-accom-logo-wide.webp" alt=""/><span className="brand-name">GOLD COAST<br/><small>ACCOM</small></span></a><p>Boutique stays and memorable local experiences, thoughtfully curated on the Gold Coast.</p></div><div><h3>Stay</h3><a href="/properties">All properties</a><a href="/locations">Locations</a><a href="/why-book-direct">Why book direct</a></div><div><h3>Experience</h3><a href="/experiences">All experiences</a><a href="/experiences/padel-getaway">Padel</a><a href="/concierge">Concierge</a></div><div><h3>About</h3><a href="/about">Our story</a><a href="/faqs">FAQs</a><a href="/contact">Contact</a></div><div className="footer-bottom"><span>© 2026 Gold Coast Accom</span><span><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/booking-policies">Booking policies</a></span></div></footer></>}
