export const locations = [
  { slug:"palm-beach", name:"Palm Beach", tagline:"Relaxed, local and close to the water.", intro:"A laid-back pocket of the southern Gold Coast where morning swims, neighbourhood dining and easy coastal living set the pace.", image:"https://goldcoast-accom.com.au/wp-content/uploads/2026/02/Palm-Beach.webp", highlights:["Currumbin Creek mornings","Walkable cafés and dining","Easy access to the southern beaches"], seo:"Palm Beach holiday accommodation" },
  { slug:"broadbeach", name:"Broadbeach", tagline:"Beach, dining and city energy.", intro:"Stay within an easy walk of golden sand, celebrated restaurants, shopping and the Gold Coast Convention and Exhibition Centre.", image:"https://goldcoast-accom.com.au/wp-content/uploads/2026/02/Broadbeach.jpg", highlights:["Dining on Oracle Boulevard","Patrolled swimming beaches","Pacific Fair and The Star nearby"], seo:"Broadbeach holiday apartments" },
  { slug:"burleigh-heads", name:"Burleigh Heads", tagline:"Iconic coastline and village charm.", intro:"The classic Gold Coast mix: a world-famous headland, protected swimming, village energy and some of the city’s best places to eat.", image:"https://goldcoast-accom.com.au/wp-content/uploads/2026/02/Burleigh.jpg", highlights:["Burleigh Head National Park","Village markets and boutiques","Restaurants from sunrise to late"], seo:"Burleigh Heads holiday accommodation" },
  { slug:"bilinga", name:"Bilinga", tagline:"Quiet beachfront living in the south.", intro:"A calmer stretch of coastline for guests who want long beach walks, oceanfront bike paths and room to slow down.", image:"https://goldcoast-accom.com.au/wp-content/uploads/2026/01/48447-270083-hg2BBOOgEL7-tApmwQ-lrhpH6a1hIoZ2Lq8DFvzkbgY-663cf7168b8c3-1024x683.webp", highlights:["Uncrowded beachfront","Coastal cycling path","Minutes from Gold Coast Airport"], seo:"Bilinga beachfront accommodation" },
];

export const experiences = [
  { slug:"padel-getaway", name:"Padel Getaway", category:"Play", tagline:"Courts, coaching and a stay to match.", description:"We’ll shape a Gold Coast padel escape around your group—from court time and coaching to accommodation, transfers and the best post-match table nearby.", image:"/assets/experience-strip-reference.png", includes:["Court bookings","Private or group coaching","Accommodation recommendations","Optional transfers and dining"] },
  { slug:"private-yacht-charter", name:"Private Yacht Charter", category:"Explore", tagline:"A private day on the Broadwater.", description:"Step aboard for an unhurried day or sunset cruise, with an itinerary matched to your group and the conditions.", image:"https://goldcoast-accom.com.au/wp-content/uploads/2024/10/yacht.png", includes:["Private vessel options","Skipper and tailored route","Catering options","Return transfers by request"] },
  { slug:"retro-defender-adventure", name:"Retro Defender Adventure", category:"Adventure", tagline:"Iconic drives and hidden coastal spots.", description:"Discover the hinterland and lesser-known corners of the coast in a classic adventure vehicle, with local stops selected around your interests.", image:"https://goldcoast-accom.com.au/wp-content/uploads/2024/10/Defender-Pic-1.jpg", includes:["Curated self-drive route","Local recommendations","Picnic or dining add-ons","Photography stops"] },
  { slug:"private-dining", name:"Private Dining", category:"Connect", tagline:"A memorable table, without leaving home.", description:"Bring the restaurant experience to your holiday home with a private chef, a menu designed for your group and all the details handled.", image:"https://goldcoast-accom.com.au/wp-content/uploads/2024/10/finedine.png", includes:["Chef matching","Tailored menu","Dietary requirements","Optional wine pairing"] },
];

export const findLocation = (slug:string) => locations.find(item => item.slug === slug);
export const findExperience = (slug:string) => experiences.find(item => item.slug === slug);
